name: Build and Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -e .

    - name: Build package
      run: python -m build

    - name: Check distribution
      run: twine check dist/*

    - name: Test package installation
      run: |
        pip install --no-index --find-links=dist/ jumpcloud-awscli
        python -c "import jumpcloud_aws_cli; print(jumpcloud_aws_cli.__version__)"
        

    - name: Publish to PyPI
      if: success() && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true